version: '3.1'
services:
  octane_nginx:
    image: nginx:alpine
    container_name: octane_nginx
    volumes:
      - '.:/var/www/html/octane-example'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './docker/nginx/logs:/var/log/nginx'
    expose:
      - 80
      - 443
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"
  octane_php82:
    build:
      context: .
      dockerfile: ./docker/php82/swoole/Dockerfile
    container_name: octane_php82
    #    restart: always
    working_dir: /var/www/html/octane-example
    command: [ "php", "artisan", "octane:start", "--watch", "--port=8000"]
    ports:
      - "80:80"
    volumes:
      - '.:/var/www/html/octane-example'
      - './docker/php82/supervisor/conf.d:/etc/supervisor/conf.d'
      - './docker/php82/supervisor/logs:/var/log/cache'
      - './docker/php82/php-fpm/conf.d/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"

  octane_mysql:
    image: quocdaijr/msql:8.0
    container_name: octane_mysql
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=12345@
      - MYSQL_DATABASE=octane-example
      - MYSQL_USER=basic-user
      - MYSQL_PASSWORD=basic-password
    expose:
      - 3306
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"

  octane_redis:
    image: redis:latest
    container_name: octane_redis
    volumes:
      - './docker/redis/data:/data'
    expose:
      - 6379
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"
