version: '3.1'
services:
  octane_nginx:
    image: nginx:alpine
    container_name: octane_nginx
    volumes:
      - '.:/var/www/html/octane-example'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - './docker/nginx/logs:/var/log/nginx'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - octane_fpm_php82
    dns:
      - 8.8.8.8
      - 4.4.4.4
    networks:
      - octane-network
  octane_fpm_php82:
    build:
      context: .
      dockerfile: ./docker/php82/php-fpm/Dockerfile
    container_name: octane_fpm_php82
    working_dir: /var/www/html/octane-example
    command: [ "/usr/sbin/php-fpm8.2", "--force-stderr"]
    ports:
      - "9000:9000"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    networks:
      - octane-network
  octane_swoole_php82:
    build:
      context: .
      dockerfile: ./docker/php82/swoole/Dockerfile
    container_name: octane_swoole_php82
    #    restart: always
    working_dir: /var/www/html/octane-example
    command: [ "php", "artisan", "octane:start", "--server=swoole", "--port=8001", "--workers=4", "--host=0.0.0.0"]
    ports:
      - "8001:8001"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    networks:
      - octane-network
  octane_roadrunner_php82:
    build:
      context: .
      dockerfile: ./docker/php82/roadrunner/Dockerfile
    container_name: octane_roadrunner_php82
    working_dir: /var/www/html/octane-example
    command: [ "php", "artisan", "octane:start", "--server=roadrunner", "--port=8002", "--workers=4", "--host=0.0.0.0"]
    ports:
      - "8002:8002"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    networks:
      - octane-network
  octane_frankenphp_php82:
    build:
      context: .
      dockerfile: ./docker/php82/frankenphp/Dockerfile
    container_name: octane_frankenphp_php82
    working_dir: /var/www/html/octane-example
    command: [ "php", "artisan", "octane:start", "--server=frankenphp", "--port=8003", "--workers=4", "--host=0.0.0.0"]
    ports:
      - "8003:8003"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    networks:
      - octane-network

networks:
  octane-network:
    driver: bridge